name: Master pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 2.7.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'

      - name: Build
        run: |
          gem install bundler -v 2.1.4
          bundle install --jobs 4 --retry 3

      - name: Run linter
        run: |
          bundle exec rake lint

      - name: Run tests
        env:
          COVERAGE: true
        run: |
          bundle exec rake spec

      - name: Upload code coverage
        uses: codecov/codecov-action@v1.0.13
